# Generated by Django 5.1.4 on 2025-01-07 12:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAuctionItem', '0002_alter_lot_year_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='year_published',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 7, 19, 14, 30, 270395)),
        ),
    ]
