# Generated by Django 5.1.4 on 2025-01-13 10:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAuctionItem', '0002_alter_lot_year_published'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Auction',
            new_name='DauGia',
        ),
        migrations.AlterField(
            model_name='lot',
            name='year_published',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 13, 17, 49, 45, 659709)),
        ),
    ]
