# Generated by Django 5.1.4 on 2025-01-13 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAuctionItem', '0003_rename_auction_daugia_alter_lot_year_published'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DauGia',
            new_name='Auction',
        ),
        migrations.AlterField(
            model_name='lot',
            name='year_published',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 13, 18, 1, 52, 982597)),
        ),
    ]
