# Generated by Django 5.1.4 on 2025-01-15 08:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAuctionItem', '0004_rename_daugia_auction_alter_lot_year_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='year_published',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 15, 15, 30, 19, 512744)),
        ),
    ]
