# Generated by Django 5.0.11 on 2025-01-21 07:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAuctionItem', '0005_alter_lot_year_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='year_published',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 21, 14, 52, 3, 689540)),
        ),
    ]
