# Generated by Django 5.0.11 on 2025-02-08 13:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAuctionItem', '0006_alter_lot_year_published'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='lot',
            name='AppAuctionI_id_e91f04_idx',
        ),
        migrations.AlterField(
            model_name='lot',
            name='year_published',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 8, 20, 32, 26, 756496)),
        ),
        migrations.AlterIndexTogether(
            name='lot',
            index_together={('id', 'slug')},
        ),
    ]
