version: '3.4'

services:
  webauction:
    image: webauction
    build:
      context: .
      dockerfile: ./Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  web:
    build: .
    container_name: django_app
    depends_on:
      - redis
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: always

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: always