# Generated by Django 5.1.4 on 2025-01-08 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='digital',
        ),
        migrations.AddField(
            model_name='product',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
