# Generated by Django 5.1.4 on 2025-01-08 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_auction_name_alter_customer_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
