# Generated by Django 5.1.4 on 2025-01-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_auction_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='hour_end',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
