# Generated by Django 5.1.4 on 2025-01-13 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auction_hour_end'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='hour_end',
        ),
    ]
